//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticketing_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laptop_Master
    {
        public int srPk { get; set; }
        public string requesterLocation { get; set; }
        public string requesterEmailID { get; set; }
        public string requestType { get; set; }
        public string issueDetails { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dateOfTravel { get; set; }
        public string laptopType { get; set; }
        public string actionTaken { get; set; }
        public Nullable<System.DateTime> dateOfClosing { get; set; }
        public string status { get; set; }
        public string isDeleted { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> sapid { get; set; }
        public string replacementType { get; set; }
        public string fromLocation { get; set; }
        public string toLocation { get; set; }
        public Nullable<bool> isLaptopRequired { get; set; }
        public Nullable<System.DateTime> laptopUpdatedDate { get; set; }
        public Nullable<System.DateTime> slaDate { get; set; }
        public string remarks { get; set; }
    }
}
