//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticketing_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location_Master
    {
        public int id { get; set; }
        public string city { get; set; }
        public string country { get; set; }
    }
}
