//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticketing_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Master
    {
        public int loginPk { get; set; }
        public string username { get; set; }
        public string loginPassword { get; set; }
        public string loginRole { get; set; }
        public string loginStatus { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string emailID { get; set; }
        public string isDeleted { get; set; }
    }
}
