//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticketing_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Onboarding_Master
    {
        public int pkID { get; set; }
        public Nullable<System.DateTime> expectedJoiningDate { get; set; }
        public string band { get; set; }
        public string personalSubArea { get; set; }
        public string joiningL4 { get; set; }
        public string reportingManager { get; set; }
        public string recruiter { get; set; }
        public string srNumber { get; set; }
        public string contactNumber { get; set; }
        public string autoReqID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string emailID { get; set; }
        public string isDeleted { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> actualJoiningDate { get; set; }
        public Nullable<int> orderID { get; set; }
        public Nullable<System.DateTime> laptopRequestUpdatedDate { get; set; }
        public string laptopRequestUpdateRemarks { get; set; }
        public Nullable<int> sapID { get; set; }
        public Nullable<System.DateTime> sapIDUpdatedDate { get; set; }
        public string sapIDRemarks { get; set; }
        public Nullable<System.DateTime> gitUpdatedDate { get; set; }
        public Nullable<System.DateTime> laptopDispatchDate { get; set; }
        public Nullable<System.DateTime> laptopCollectionDate { get; set; }
        public Nullable<int> prevStatus { get; set; }
        public Nullable<System.DateTime> RENEGEUpdatedDate { get; set; }
        public string RENEGERemarks { get; set; }
    }
}
